name: TCI SIT

on:
  push:
   # inputs:
   #   branch_name:
   #     description: Branch Name
   #     required: true
   #   build_number:
   #     description: Build Number
   #     required: false
   #   workflow_type:
   #     description: Workflow Type
   #     required: true
   #     default: Build-Deploy
   #   instance_count:
   #     description: Instance Count
   #     required: true
   #     default: 0
   #   instance_name:
   #     description: 'Instance-Name'
   #     required: false
   #   Sharedmodule_instance_name:
   #     description: 'Shared-module-Instance-Name'
   #     required: false
jobs:
    steps:
    - name: Read CSV
      run: |
        python new.py
      env:
        csv_path: calling-workflows/Inputs.csv
      
  TCI-SIT:
    uses: Sanofi-GitHub/chc-devops-scripts/.github/workflows/TCI-SIT.yml@main
    with:
      DOCKER_IMAGE: sanofi-docker-chc-tibco-local.jfrog.io/build-images/sanofi-chc-build-base:v1.0.0
      INTERFACE_NAME: bw.mc-WEBB-MATMAS
    secrets:
      CHC_HTTP_PROXY: ${{ secrets.CHC_HTTP_PROXY }}
      CHC_HTTPS_PROXY: ${{ secrets.CHC_HTTPS_PROXY }}
      CHC_GITHUB_PAT: ${{ secrets.CHC_GITHUB_PAT }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      SIT_TCI_CLIENT_ID: ${{ secrets.SIT_TCI_CLIENT_ID }}
      SIT_TCI_CLIENT_SECRET: ${{ secrets.SIT_TCI_CLIENT_SECRET }}
