name: Merge Conflict Resolution
 
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
 
jobs:
  merge-conflict-resolution:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
      
    - name: Run merge conflict resolution script
      run: |
        if bash resolve_merge_conflicts.sh; then
          echo "Merge conflicts resolved successfully."
        else
          echo "Merge conflicts detected. Sending email notification..."
          echo "Merge conflicts detected in repository: $(git rev-parse --show-toplevel)" | mail -s "Merge Conflict Notification" bhavana.kasula@gmail.com
          exit 1
        fi
