name: Merge Conflict Detection
 
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
 
jobs:
  merge-conflict-detection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        
    - name: Install git
      run: sudo apt-get install git -y
      
    - name: Merge PR
      run: git merge ${{ github.event.pull_request.head.sha }}
      
    - name: Check for merge conflict
      run: |
        if git diff --check | grep -q '<<<<<<<'; then
          echo "Merge conflict detected, sending email notification..."
          echo "Merge conflict detected in repository: $(git rev-parse --show-toplevel)" | mail -s "Merge Conflict Notification" bhannu.kasula@gmail.com
        else
          echo "No merge conflict detected."
        fi
