name: Check Merge Conflicts
on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Check for merge conflicts
        run: |
          git fetch origin master
          if ! git merge --check origin/master; then
            echo "There are merge conflicts!"
            exit 1
          fi
          echo "No merge conflicts detected."
