name: Merge Conflict Detection
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  merge-conflict-detection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Check for merge conflict
      run: |
        # Check for unmerged files, indicating merge conflicts
        if git ls-files -u | grep -q '^'; then
          echo "Merge conflict detected, sending email notification..."
          echo "Merge conflict detected in repository: $(git rev-parse --show-toplevel)" | mail -s "Merge Conflict Notification" bhannu.kasula@gmail.com
        else
          echo "No merge conflict detected."
          exit 78  # Exit with a neutral status code to prevent further execution of the workflow
        fi
