
name: Repositorylist-CHC

on:
  push:
   branches:
     - sample-list
   paths:
     - "**/repo_list_new.yml"
     - "**/repo-list-new.sh"
env:      
  HTTP_PROXY: ${{ secrets.CHC_HTTP_PROXY }}
  HTTPS_PROXY: ${{ secrets.CHC_HTTPS_PROXY }}
  GITHUB_PAT: ${{ secrets.CHC_GITHUB_PAT }}
  JFROG_USERNAME:  ${{ secrets.JFROG_USERNAME }}
  JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  WORKSPACE: ${{ github.workspace }}
  GIT_USERNAME:  ${{ secrets.CHC_GIT_CONFIG_NAME }}
  GIT_EMAIL: ${{ secrets.CHC_GIT_CONFIG_EMAIL }}  
  REPONAME: ${{ github.event.repository.name }}
  GH_TOKEN: ${{ secrets.CHC_GITHUB_PAT }}

jobs:
  Get_repo_list_using_Github_CLI:
    runs-on: ['atmos-aws-arc-runner-set']
    container:
      image: sanofi-docker-chc-tibco-local.jfrog.io/build-images/sanofi-chc-build-base:v1.0.0
      credentials:
        username: ${{ env.JFROG_USERNAME }}
        password: ${{ env.JFROG_TOKEN }}
    steps:
      - name: add repo to safe directory
        run: |
          git config --global --add safe.directory /__w/${REPONAME}/${REPONAME}
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: 'true'
          ref: ${{ github.ref }}
          token: ${{ env.GITHUB_PAT }}
          
      - name: install GH cli 
        run: | 
             VERSION=`curl  "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-` 
             echo $VERSION
             ### With curl ###
             curl -sSL https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz -o gh_${VERSION}_linux_amd64.tar.gz
             tar xvf gh_${VERSION}_linux_amd64.tar.gz
             sudo cp gh_${VERSION}_linux_amd64/bin/gh /usr/local/bin/
             gh version

      - name: Get Repo List in the org
        run: |
          cd ${WORKSPACE}/cicd-scripts
          bash repo-list-new.sh ${{ env.GITHUB_PAT }}
          ls -lah repo_list.csv
          
      - uses: actions/upload-artifact@v2 # Uplaod screenshots to Actions Artifacts via actions/upload-artifact@v2
        with:
               path: ${{ github.workspace }}/cicd-scripts/repo_list.csv
               name: repo_list
          
      - name: Download a single artifacts
        uses: actions/download-artifact@v3
        with:
             name: repo_list
             path: ${{ github.workspace }}/
             
