name: TCI SIT

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch Name
        required: true
      build_number:
        description: Build Number
        required: false
      workflow_type:
        description: Workflow Type
        required: true
        default: Build-Deploy
      instance_count:
        description: Instance Count
        required: true
        default: 0
      instance_name:
        description: 'Instance-Name'
        required: false
      Sharedmodule_instance_name:
        description: 'Shared-module-Instance-Name'
        required: false
jobs:
  TCI-SIT:
    uses: Sanofi-GitHub/chc-devops-scripts/.github/workflows/TCI-SIT.yml@main
    with:
      DOCKER_IMAGE: sanofi-docker-chc-tibco-local.jfrog.io/build-images/sanofi-chc-build-base:v1.0.0
      INTERFACE_NAME: bw.mc-WEBB-MATMAS
    secrets:
      CHC_HTTP_PROXY: ${{ secrets.CHC_HTTP_PROXY }}
      CHC_HTTPS_PROXY: ${{ secrets.CHC_HTTPS_PROXY }}
      CHC_GITHUB_PAT: ${{ secrets.CHC_GITHUB_PAT }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      SIT_TCI_CLIENT_ID: ${{ secrets.SIT_TCI_CLIENT_ID }}
      SIT_TCI_CLIENT_SECRET: ${{ secrets.SIT_TCI_CLIENT_SECRET }}


import csv
import os
import sys

print('Get current working directory : ', os.getcwd())
csv_file = os.path.abspath('Inputs.csv')
print('here is the', csv_file)
with open(csv_file, "r") as file:
    csv_reader = csv.DictReader(file)
    row = next(csv_reader, {})
    
    branch_name = row.get('BranchName', '')
    build_number = row.get('BuildNumber', '')
    workflow_type = row.get('WorkflowType', '')
    instance_name = row.get('InstanceName', '')
    instance_count = row.get('InstanceCount', '')
    shared_module_instance_name = row.get('SharedModuleInstanceName', '')

    csv_values = ",".join([branch_name, build_number, workflow_type, instance_name, instance_count, shared_module_instance_name])
    print("Original CSV Values:", csv_values)

    print("Branch Name Variable:", branch_name)
    print("Build Number Variable:", build_number)
    print("Workflow Type Variable:", workflow_type)
    print("Instance Name Variable:", instance_name)
    print("Instance Count Variable:", instance_count)
    print("Shared Module Instance Name Variable:", shared_module_instance_name)
