name: TCI SIT
on:
  push:
    branches:
      - main
   # inputs:
   #   branch_name:
   #     description: Branch Name
   #     required: true
   #   build_number:
   #     description: Build Number
   #     required: false
   #   workflow_type:
   #     description: Workflow Type
   #     required: true
   #     default: Build-Deploy
   #   instance_count:
   #     description: Instance Count
   #     required: true
   #     default: 0
   #   instance_name:
   #     description: 'Instance-Name'
   #     required: false
   #   Sharedmodule_instance_name:
   #     description: 'Shared-module-Instance-Name'
   #     required: false
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List repo contents
      run: ls -R

    - name: make script executable
      run: chmod +x sample.py

    - name: execute python script
      run: ./sample.py
      
 #   - name: Read CSV
 #     run: |
 #       csv_values= $(python sample.py)
 #       echo "CSV value: $csv_values"
 #     env:
 #       csv_path: .github/workflows/Inputs.csv

    

        
